title: Autocall
description: Autocall's home for tutorials and projects
theme: just-the-docs

baseurl: ""
url: https://auto-call.github.io

permalink: pretty

aux_links:
  My GitHub: https://github.com/auto-call
aux_links_new_tab: true

favicon_ico: "/assets/images/favicon.png"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y"

plugins:
  - jekyll-target-blank
